apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-hostnetwork
spec:
  validationFailureAction: Enforce
  rules:
    - name: block-hostnetwork-true
      match:
        any:
        - resources:
            kinds:
              - Pod
      validate:
        message: "HostNetwork must not be enabled"
        deny:
          conditions:
            any:
              - key: "{{ request.object.spec.hostNetwork || false }}"
                operator: Equals
                value: true